/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MediaToDocsIndexRouteImport } from './routes/media-to-docs/index'
import { Route as ConvertIndexRouteImport } from './routes/convert/index'
import { Route as MediaToDocsCacheManagementIndexRouteImport } from './routes/media-to-docs/cache-management/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaToDocsIndexRoute = MediaToDocsIndexRouteImport.update({
  id: '/media-to-docs/',
  path: '/media-to-docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertIndexRoute = ConvertIndexRouteImport.update({
  id: '/convert/',
  path: '/convert/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaToDocsCacheManagementIndexRoute =
  MediaToDocsCacheManagementIndexRouteImport.update({
    id: '/media-to-docs/cache-management/',
    path: '/media-to-docs/cache-management/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convert': typeof ConvertIndexRoute
  '/media-to-docs': typeof MediaToDocsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/media-to-docs/cache-management': typeof MediaToDocsCacheManagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convert': typeof ConvertIndexRoute
  '/media-to-docs': typeof MediaToDocsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/media-to-docs/cache-management': typeof MediaToDocsCacheManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/convert/': typeof ConvertIndexRoute
  '/media-to-docs/': typeof MediaToDocsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/media-to-docs/cache-management/': typeof MediaToDocsCacheManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/convert'
    | '/media-to-docs'
    | '/settings'
    | '/media-to-docs/cache-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/convert'
    | '/media-to-docs'
    | '/settings'
    | '/media-to-docs/cache-management'
  id:
    | '__root__'
    | '/'
    | '/convert/'
    | '/media-to-docs/'
    | '/settings/'
    | '/media-to-docs/cache-management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConvertIndexRoute: typeof ConvertIndexRoute
  MediaToDocsIndexRoute: typeof MediaToDocsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  MediaToDocsCacheManagementIndexRoute: typeof MediaToDocsCacheManagementIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-to-docs/': {
      id: '/media-to-docs/'
      path: '/media-to-docs'
      fullPath: '/media-to-docs'
      preLoaderRoute: typeof MediaToDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert/': {
      id: '/convert/'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-to-docs/cache-management/': {
      id: '/media-to-docs/cache-management/'
      path: '/media-to-docs/cache-management'
      fullPath: '/media-to-docs/cache-management'
      preLoaderRoute: typeof MediaToDocsCacheManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConvertIndexRoute: ConvertIndexRoute,
  MediaToDocsIndexRoute: MediaToDocsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  MediaToDocsCacheManagementIndexRoute: MediaToDocsCacheManagementIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
