/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PromptOptimizerIndexRouteImport } from './routes/prompt-optimizer/index'
import { Route as MediaToDocsIndexRouteImport } from './routes/media-to-docs/index'
import { Route as GitProjectManagerIndexRouteImport } from './routes/git-project-manager/index'
import { Route as DocsManagerIndexRouteImport } from './routes/docs-manager/index'
import { Route as BilibiliDownloaderIndexRouteImport } from './routes/bilibili-downloader/index'
import { Route as VoiceCloningTrainingIndexRouteImport } from './routes/voice-cloning/training/index'
import { Route as VoiceCloningSynthesisIndexRouteImport } from './routes/voice-cloning/synthesis/index'
import { Route as MediaToDocsConvertHistoryIndexRouteImport } from './routes/media-to-docs/convert-history/index'
import { Route as GitProjectManagerWeeklyReportIndexRouteImport } from './routes/git-project-manager/weekly-report/index'
import { Route as DocsManagerTemplatesIndexRouteImport } from './routes/docs-manager/templates/index'
import { Route as GitProjectManagerProjectIdRouteImport } from './routes/git-project-manager/project.$id'
import { Route as DocsManagerEditorDocIdRouteImport } from './routes/docs-manager/editor.$docId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptOptimizerIndexRoute = PromptOptimizerIndexRouteImport.update({
  id: '/prompt-optimizer/',
  path: '/prompt-optimizer/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaToDocsIndexRoute = MediaToDocsIndexRouteImport.update({
  id: '/media-to-docs/',
  path: '/media-to-docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const GitProjectManagerIndexRoute = GitProjectManagerIndexRouteImport.update({
  id: '/git-project-manager/',
  path: '/git-project-manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsManagerIndexRoute = DocsManagerIndexRouteImport.update({
  id: '/docs-manager/',
  path: '/docs-manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const BilibiliDownloaderIndexRoute = BilibiliDownloaderIndexRouteImport.update({
  id: '/bilibili-downloader/',
  path: '/bilibili-downloader/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceCloningTrainingIndexRoute =
  VoiceCloningTrainingIndexRouteImport.update({
    id: '/voice-cloning/training/',
    path: '/voice-cloning/training/',
    getParentRoute: () => rootRouteImport,
  } as any)
const VoiceCloningSynthesisIndexRoute =
  VoiceCloningSynthesisIndexRouteImport.update({
    id: '/voice-cloning/synthesis/',
    path: '/voice-cloning/synthesis/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MediaToDocsConvertHistoryIndexRoute =
  MediaToDocsConvertHistoryIndexRouteImport.update({
    id: '/media-to-docs/convert-history/',
    path: '/media-to-docs/convert-history/',
    getParentRoute: () => rootRouteImport,
  } as any)
const GitProjectManagerWeeklyReportIndexRoute =
  GitProjectManagerWeeklyReportIndexRouteImport.update({
    id: '/git-project-manager/weekly-report/',
    path: '/git-project-manager/weekly-report/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsManagerTemplatesIndexRoute =
  DocsManagerTemplatesIndexRouteImport.update({
    id: '/docs-manager/templates/',
    path: '/docs-manager/templates/',
    getParentRoute: () => rootRouteImport,
  } as any)
const GitProjectManagerProjectIdRoute =
  GitProjectManagerProjectIdRouteImport.update({
    id: '/git-project-manager/project/$id',
    path: '/git-project-manager/project/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsManagerEditorDocIdRoute = DocsManagerEditorDocIdRouteImport.update({
  id: '/docs-manager/editor/$docId',
  path: '/docs-manager/editor/$docId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bilibili-downloader': typeof BilibiliDownloaderIndexRoute
  '/docs-manager': typeof DocsManagerIndexRoute
  '/git-project-manager': typeof GitProjectManagerIndexRoute
  '/media-to-docs': typeof MediaToDocsIndexRoute
  '/prompt-optimizer': typeof PromptOptimizerIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/docs-manager/editor/$docId': typeof DocsManagerEditorDocIdRoute
  '/git-project-manager/project/$id': typeof GitProjectManagerProjectIdRoute
  '/docs-manager/templates': typeof DocsManagerTemplatesIndexRoute
  '/git-project-manager/weekly-report': typeof GitProjectManagerWeeklyReportIndexRoute
  '/media-to-docs/convert-history': typeof MediaToDocsConvertHistoryIndexRoute
  '/voice-cloning/synthesis': typeof VoiceCloningSynthesisIndexRoute
  '/voice-cloning/training': typeof VoiceCloningTrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bilibili-downloader': typeof BilibiliDownloaderIndexRoute
  '/docs-manager': typeof DocsManagerIndexRoute
  '/git-project-manager': typeof GitProjectManagerIndexRoute
  '/media-to-docs': typeof MediaToDocsIndexRoute
  '/prompt-optimizer': typeof PromptOptimizerIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/docs-manager/editor/$docId': typeof DocsManagerEditorDocIdRoute
  '/git-project-manager/project/$id': typeof GitProjectManagerProjectIdRoute
  '/docs-manager/templates': typeof DocsManagerTemplatesIndexRoute
  '/git-project-manager/weekly-report': typeof GitProjectManagerWeeklyReportIndexRoute
  '/media-to-docs/convert-history': typeof MediaToDocsConvertHistoryIndexRoute
  '/voice-cloning/synthesis': typeof VoiceCloningSynthesisIndexRoute
  '/voice-cloning/training': typeof VoiceCloningTrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bilibili-downloader/': typeof BilibiliDownloaderIndexRoute
  '/docs-manager/': typeof DocsManagerIndexRoute
  '/git-project-manager/': typeof GitProjectManagerIndexRoute
  '/media-to-docs/': typeof MediaToDocsIndexRoute
  '/prompt-optimizer/': typeof PromptOptimizerIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/docs-manager/editor/$docId': typeof DocsManagerEditorDocIdRoute
  '/git-project-manager/project/$id': typeof GitProjectManagerProjectIdRoute
  '/docs-manager/templates/': typeof DocsManagerTemplatesIndexRoute
  '/git-project-manager/weekly-report/': typeof GitProjectManagerWeeklyReportIndexRoute
  '/media-to-docs/convert-history/': typeof MediaToDocsConvertHistoryIndexRoute
  '/voice-cloning/synthesis/': typeof VoiceCloningSynthesisIndexRoute
  '/voice-cloning/training/': typeof VoiceCloningTrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bilibili-downloader'
    | '/docs-manager'
    | '/git-project-manager'
    | '/media-to-docs'
    | '/prompt-optimizer'
    | '/settings'
    | '/docs-manager/editor/$docId'
    | '/git-project-manager/project/$id'
    | '/docs-manager/templates'
    | '/git-project-manager/weekly-report'
    | '/media-to-docs/convert-history'
    | '/voice-cloning/synthesis'
    | '/voice-cloning/training'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bilibili-downloader'
    | '/docs-manager'
    | '/git-project-manager'
    | '/media-to-docs'
    | '/prompt-optimizer'
    | '/settings'
    | '/docs-manager/editor/$docId'
    | '/git-project-manager/project/$id'
    | '/docs-manager/templates'
    | '/git-project-manager/weekly-report'
    | '/media-to-docs/convert-history'
    | '/voice-cloning/synthesis'
    | '/voice-cloning/training'
  id:
    | '__root__'
    | '/'
    | '/bilibili-downloader/'
    | '/docs-manager/'
    | '/git-project-manager/'
    | '/media-to-docs/'
    | '/prompt-optimizer/'
    | '/settings/'
    | '/docs-manager/editor/$docId'
    | '/git-project-manager/project/$id'
    | '/docs-manager/templates/'
    | '/git-project-manager/weekly-report/'
    | '/media-to-docs/convert-history/'
    | '/voice-cloning/synthesis/'
    | '/voice-cloning/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BilibiliDownloaderIndexRoute: typeof BilibiliDownloaderIndexRoute
  DocsManagerIndexRoute: typeof DocsManagerIndexRoute
  GitProjectManagerIndexRoute: typeof GitProjectManagerIndexRoute
  MediaToDocsIndexRoute: typeof MediaToDocsIndexRoute
  PromptOptimizerIndexRoute: typeof PromptOptimizerIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  DocsManagerEditorDocIdRoute: typeof DocsManagerEditorDocIdRoute
  GitProjectManagerProjectIdRoute: typeof GitProjectManagerProjectIdRoute
  DocsManagerTemplatesIndexRoute: typeof DocsManagerTemplatesIndexRoute
  GitProjectManagerWeeklyReportIndexRoute: typeof GitProjectManagerWeeklyReportIndexRoute
  MediaToDocsConvertHistoryIndexRoute: typeof MediaToDocsConvertHistoryIndexRoute
  VoiceCloningSynthesisIndexRoute: typeof VoiceCloningSynthesisIndexRoute
  VoiceCloningTrainingIndexRoute: typeof VoiceCloningTrainingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-optimizer/': {
      id: '/prompt-optimizer/'
      path: '/prompt-optimizer'
      fullPath: '/prompt-optimizer'
      preLoaderRoute: typeof PromptOptimizerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-to-docs/': {
      id: '/media-to-docs/'
      path: '/media-to-docs'
      fullPath: '/media-to-docs'
      preLoaderRoute: typeof MediaToDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/git-project-manager/': {
      id: '/git-project-manager/'
      path: '/git-project-manager'
      fullPath: '/git-project-manager'
      preLoaderRoute: typeof GitProjectManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs-manager/': {
      id: '/docs-manager/'
      path: '/docs-manager'
      fullPath: '/docs-manager'
      preLoaderRoute: typeof DocsManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilibili-downloader/': {
      id: '/bilibili-downloader/'
      path: '/bilibili-downloader'
      fullPath: '/bilibili-downloader'
      preLoaderRoute: typeof BilibiliDownloaderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-cloning/training/': {
      id: '/voice-cloning/training/'
      path: '/voice-cloning/training'
      fullPath: '/voice-cloning/training'
      preLoaderRoute: typeof VoiceCloningTrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-cloning/synthesis/': {
      id: '/voice-cloning/synthesis/'
      path: '/voice-cloning/synthesis'
      fullPath: '/voice-cloning/synthesis'
      preLoaderRoute: typeof VoiceCloningSynthesisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-to-docs/convert-history/': {
      id: '/media-to-docs/convert-history/'
      path: '/media-to-docs/convert-history'
      fullPath: '/media-to-docs/convert-history'
      preLoaderRoute: typeof MediaToDocsConvertHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/git-project-manager/weekly-report/': {
      id: '/git-project-manager/weekly-report/'
      path: '/git-project-manager/weekly-report'
      fullPath: '/git-project-manager/weekly-report'
      preLoaderRoute: typeof GitProjectManagerWeeklyReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs-manager/templates/': {
      id: '/docs-manager/templates/'
      path: '/docs-manager/templates'
      fullPath: '/docs-manager/templates'
      preLoaderRoute: typeof DocsManagerTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/git-project-manager/project/$id': {
      id: '/git-project-manager/project/$id'
      path: '/git-project-manager/project/$id'
      fullPath: '/git-project-manager/project/$id'
      preLoaderRoute: typeof GitProjectManagerProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs-manager/editor/$docId': {
      id: '/docs-manager/editor/$docId'
      path: '/docs-manager/editor/$docId'
      fullPath: '/docs-manager/editor/$docId'
      preLoaderRoute: typeof DocsManagerEditorDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BilibiliDownloaderIndexRoute: BilibiliDownloaderIndexRoute,
  DocsManagerIndexRoute: DocsManagerIndexRoute,
  GitProjectManagerIndexRoute: GitProjectManagerIndexRoute,
  MediaToDocsIndexRoute: MediaToDocsIndexRoute,
  PromptOptimizerIndexRoute: PromptOptimizerIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  DocsManagerEditorDocIdRoute: DocsManagerEditorDocIdRoute,
  GitProjectManagerProjectIdRoute: GitProjectManagerProjectIdRoute,
  DocsManagerTemplatesIndexRoute: DocsManagerTemplatesIndexRoute,
  GitProjectManagerWeeklyReportIndexRoute:
    GitProjectManagerWeeklyReportIndexRoute,
  MediaToDocsConvertHistoryIndexRoute: MediaToDocsConvertHistoryIndexRoute,
  VoiceCloningSynthesisIndexRoute: VoiceCloningSynthesisIndexRoute,
  VoiceCloningTrainingIndexRoute: VoiceCloningTrainingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
