name: Build Electron App

on:
  # 触发条件
  pull_request:
    branches: [main]

  # 允许手动触发
  workflow_dispatch:

jobs:
  build:
    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.title, '[skip build]')
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build client
        run: pnpm build:client

      - name: Build app for Pull Request
        if: github.event_name == 'pull_request'
        run: pnpm dist

      - name: Build and Publish Release
        if: github.event_name == 'workflow_dispatch'
        run: pnpm release:ci
        env:
          # GitHub token for release
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # macOS 代码签名（可选，需要配置 secrets）
          # CSC_LINK: ${{ secrets.MAC_CERT_P12_BASE64 }}
          # CSC_KEY_PASSWORD: ${{ secrets.MAC_CERT_PASSWORD }}
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_APP_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}

      - name: Upload artifacts for debugging
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: |
            release/*.exe
            release/*.dmg
            release/*.zip
            release/*.AppImage
            release/*.deb
            release/latest*.yml
          if-no-files-found: ignore
